    services:
      - type: web
        name: voicesentinal-app
        env: python
        # Ensure your runtime.txt specifies a compatible Python version (e.g., python-3.10.13)
        # buildCommand: pip install -r requirements.txt # This is the default if not specified, but good to be explicit
        startCommand: python app.py --bind 0.0.0.0:$PORT
        envVars:
          - key: FLASK_SECRET_KEY
            generateValue: true # Render will generate a strong secret key for you
          - key: MONGO_UR
            value: mongodb+srv://jahanvi:<9541350110>@cluster0.gpegtup.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
          - key: NEWS_API_KEY
            value: 4004719a0aa54f07868c82c0aabc8e88 # Replace with your actual NewsAPI.org key
          # Add any other environment variables your app needs
        autoDeploy: true # Automatically deploy on new commits to main branch
        # healthCheckPath: /api/current_user # Optional: Add a health check endpoint if you have one
    
